### PR TITLE
display total vote count

### PR DESCRIPTION
**Pull request by gidsg**
By popular request... display total vote count CC @alastairjardine @gtrufitt 
screen shot 2016-06-13 at 13 10 21

### CODE REVIEW

**Comment by gtrufitt** [comment]
I like it! My only question would be whether that would be confusing as it looks like it's attached to the 'blue' bar - maybe a little more spacing and a label 'Total' would fix that @alastairjardine ? Otherwise 👍

**Comment by gidsg** [comment]
Yeah, I did think about adding an `<hr>` or something to separate it more. Will ask @alastairjardine

**Comment by alastairjardine** [comment]
Good paging skills.

We need to shift the blue bar to the top anyway, as per our design guidelines (which I forgot...ooops).

An option might be putting it as a subhead below the "You voted for...x". Also, spot the enhancement ;)

vote widge

**Comment by alastairjardine** [comment]
Or 
vote widge copy

...might make more sense. There's a chance people could assume `xx votes total`  = for that option. This design is a bit less ambiguous

**Comment by gidsg** [comment]
@alastairjardine I think it might be a bit noisy to show the counts for each option? Twitter only shows the total count for example:
screen shot 2016-06-13 at 15 20 23

**Comment by gtrufitt** [comment]
I think I agree with Gideon on only show the total count (if people want to know count per answer, they can do the calculations :D) - but I agree with Alastair on this positioning:

image

**Comment by alastairjardine** [comment]
Sure. I can cope with the extra information :) V happy to go with the simple version though!

**Comment by alastairjardine** [comment]
@gidsg Just noticed the baseline is out for the % against the bar. Can you have a fiddle?

**Comment by nicl** [comment]
I would put the count in brackets next to the percentage. E.g

    ----- 84% (93 votes)
    --- 16% (20 votes)

(Don't check the maths on those numbers.)

**Comment by gidsg** [comment]
OK, @alastairjardine I have made the suggested tweaks now.
screen shot 2016-06-14 at 10 06 59

**Pull request merged**
